name: ielts_listening_web
description: A Flutter app for English Vocabulary Learning.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.0+2
  provider: ^6.1.1
  flutter_tts: ^3.8.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true